// Shared "day in the life of an admin user" journey, reused by every
// scenario (E1-E4). Keeping it in one module means the workload mix is
// identical across scenarios: only concurrency/duration differ.
import http from 'k6/http';
import { check, sleep } from 'k6';
import {
  BASE_URL,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  THINK_TIME_MIN,
  THINK_TIME_MAX,
} from './config.js';

// A fixed search term guaranteed to match the seeded "LT " rows (see
// seed.sql), so the search step always exercises a realistic, non-trivial
// result set instead of an accidental empty page.
const SEARCH_TERM = 'LT';

// Ids of the rows seed.sql inserted, generated by seed.sql itself as
// load-tests/seed-data.json. Falls back to the pre-existing seed row (id 1)
// so scripts still run (against a near-empty DB) before seed.sql has been
// executed -- e.g. while just reviewing/linting the scripts in commit 1.
//
// `open()` must be called at init time (top level of the module), not
// inside a function -- k6 resolves the relative path against this file's
// own directory.
let seedData = { assetIds: [1], custodianIds: [1] };
try {
  seedData = JSON.parse(open('./seed-data.json'));
} catch (_e) {
  // seed-data.json not generated yet; fall back to the defaults above.
}

function randomFrom(list) {
  return list[Math.floor(Math.random() * list.length)];
}

function think() {
  sleep(THINK_TIME_MIN + Math.random() * (THINK_TIME_MAX - THINK_TIME_MIN));
}

// Builds a distinct X-Forwarded-For per VU so the backend's throttler
// (`ThrottlerModule.forRoot` in backend/src/app.module.ts: 60 req/min,
// tracked per client IP -- see the "Throttling" section of the README for
// how NestJS actually keys that bucket) treats each VU as an independent
// client, the way distinct real users behind the public-sector network
// would appear. `backend/src/config/trust-proxy.config.ts` sets
// `trust proxy = 1`, so Express reads the client IP from this header.
//
// The subnet octet lets this scale past 254 concurrent VUs without
// colliding (not needed for E1-E4's 1/10/50/20 VUs, but cheap to get right).
export function xffForVU(vu) {
  const subnet = Math.floor((vu - 1) / 250);
  const host = ((vu - 1) % 250) + 1;
  return `10.0.${subnet}.${host}`;
}

// Logs in once and returns the bearer token. Login is deliberately EXCLUDED
// from the per-iteration workload mix below and called only once per test
// run, from setup() -- see each scenario's setup(). Two reasons:
//   1. `POST /auth/login` carries its own strict throttle
//      (`@Throttle({ default: { limit: 5, ttl: 60000 } })` in
//      auth.controller.ts) -- 5/min per client IP. Logging in on every
//      iteration, from many VUs, would 429 almost immediately and the
//      failures would be login-throttle noise, not a signal about the
//      endpoints we actually want to measure (stats/list/search/detail).
//   2. It is realistic: a real admin logs in once per session and keeps
//      working, not once per page view.
// All VUs share the one resulting token; each VU still gets its own
// X-Forwarded-For (see xffForVU), so the *rate limiter* still sees distinct
// clients even though the *application* sees one authenticated user.
export function login(xff) {
  const res = http.post(
    `${BASE_URL}/auth/login`,
    JSON.stringify({ email: ADMIN_EMAIL, password: ADMIN_PASSWORD }),
    {
      headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': xff },
      tags: { endpoint: 'auth_login' },
    },
  );
  check(res, { 'login: status 200': (r) => r.status === 200 });
  if (res.status !== 200 || !res.body) {
    return undefined;
  }
  const body = res.json();
  return body && body.accessToken;
}

// One authenticated pass through the endpoints named in the Decisions
// section of odd/tasks/load-tests.md: dashboard stats, a paginated list, a
// search, an asset detail, a custodian's assigned equipment, then the
// anonymous public catalog (unauthenticated, matches the public landing
// page added in commit 249e968).
//
// `GET /custodians/:id` (ADMIN-only) is the real "custodian's assets"
// route: CustodiansController has no separate `/custodians/:id/assets`
// endpoint. CustodiansService#findOne includes `assets: true`
// (backend/src/custodians/custodians.service.ts), and the frontend's
// `/admin/custodians/[id]/assets` page reads `custodian.assets` straight off
// that response (frontend/src/app/admin/custodians/[id]/assets/page.tsx).
export function runJourney(token, vu) {
  const xff = xffForVU(vu);
  const authHeaders = { Authorization: `Bearer ${token}`, 'X-Forwarded-For': xff };

  let res = http.get(`${BASE_URL}/assets/stats`, {
    headers: authHeaders,
    tags: { endpoint: 'assets_stats' },
  });
  check(res, { 'assets/stats: status 200': (r) => r.status === 200 });
  think();

  res = http.get(`${BASE_URL}/assets?page=1&limit=20`, {
    headers: authHeaders,
    tags: { endpoint: 'assets_list' },
  });
  check(res, { 'assets list: status 200': (r) => r.status === 200 });
  think();

  res = http.get(
    `${BASE_URL}/assets?search=${encodeURIComponent(SEARCH_TERM)}`,
    { headers: authHeaders, tags: { endpoint: 'assets_search' } },
  );
  check(res, { 'assets search: status 200': (r) => r.status === 200 });
  think();

  const assetId = randomFrom(seedData.assetIds);
  res = http.get(`${BASE_URL}/assets/${assetId}`, {
    headers: authHeaders,
    tags: { endpoint: 'assets_detail' },
  });
  check(res, { 'asset detail: status 200': (r) => r.status === 200 });
  think();

  const custodianId = randomFrom(seedData.custodianIds);
  res = http.get(`${BASE_URL}/custodians/${custodianId}`, {
    headers: authHeaders,
    tags: { endpoint: 'custodian_assets' },
  });
  check(res, { 'custodian assets: status 200': (r) => r.status === 200 });
  think();

  res = http.get(`${BASE_URL}/public/assets?limit=20`, {
    headers: { 'X-Forwarded-For': xff },
    tags: { endpoint: 'public_assets' },
  });
  check(res, { 'public assets: status 200': (r) => r.status === 200 });
  think();
}
